array_width = 60
attr_fn_like_width = 70
chain_width = 60
comment_width = 100
disable_all_formatting = false
edition = "2021"
error_on_line_overflow = true
fn_args_layout = "Tall"
fn_call_width = 60
force_explicit_abi = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = false
imports_granularity = "Module"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = false
max_width = 80
merge_derives = true
newline_style = "unix"
normalize_doc_attributes = true
print_misformatted_file_names = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 10
single_line_if_else_max_width = 50
struct_lit_width = 18
struct_variant_width = 35
tab_spaces = 4
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "max"
use_try_shorthand = true
version = "Two"
wrap_comments = true